#!/bin/bash
#SBATCH --job-name=train
#SBATCH -c 2
#SBATCH --gres=gpu:1
#SBATCH -p gpu
#SBATCH -t 7-0
#SBATCH --mem-per-cpu=100G
#SBATCH --output train_mir2.out

module load CUDA
# Whatever additional modules you need
 
#Executable here
keras_retinanet/bin/train.py --weights /home/barimpac/keras-retinanet/snapshots/resnet50_csv_02.h5 --epochs 68 --steps 1509 csv train_annotations2_mirror.csv class_mapping.csv
