#!/bin/bash
#SBATCH --job-name=pred
#SBATCH -o pred_out.txt
#SBATCH -p long
#SBATCH -c 4
#SBATCH -t 4-00:00:0
#SBATCH --mem-per-cpu=1000

python Predictions.py snapshots/resnet50_csv_50_13april2018.h5 Acrorad_1704-0601-8/Acrorad_1704-0601-8/Measurement_1/RAW/ testi.csv
