#!/bin/bash
#SBATCH --job-name=pred
#SBATCH -o pred_out.txt
#SBATCH -c 2
#SBATCH --gres=gpu:1
#SBATCH -p gpu
#SBATCH -t 4-00:00:0
#SBATCH --mem-per-cpu=1000

module purge
module load Python cuDNN
# Whatever additional modules you need
source ~/myTensorflow/bin/activate

python Predictions_ukko.py snapshots/resnet50_csv_50_13april2018.h5 Acrorad_1704-0601-8/Acrorad_1704-0601-8/Measurement_1/RAW/ Acrorad_1704-0601-8/predictions testi.csv
