#!/bin/bash
#SBATCH --job-name=test
#SBATCH -o test_out.txt
#SBATCH -c 2
#SBATCH --gres=gpu:1
#SBATCH -p gpu
#SBATCH -t 10:00
#SBATCH --mem-per-cpu=1000

module purge
module load Python cuDNN
# Whatever additional modules you need
source ~/myTensorflow/bin/activate

keras_retinanet/bin/evaluate.py --save-path ~/results/squares csv test_annotation_multi.csv csv/class_mapping_multi.csv snapshots/squares/resnet50_csv_50.h5
