#!/bin/bash
#SBATCH --job-name=test
#SBATCH -o test_out.txt
#SBATCH -p test
#SBATCH -c 4
#SBATCH -t 10:00
#SBATCH --mem-per-cpu=1000

keras_retinanet/bin/evaluate.py --save-path ~/mirrored_more/ csv test_annotations.csv class_mapping.csv snapshots/resnet50_csv_08.h5
