#!/bin/bash
#SBATCH --job-name=test
#SBATCH -o test_out.txt
#SBATCH -p test
#SBATCH -c 4
#SBATCH -t 10:00
#SBATCH --mem-per-cpu=1000

keras_retinanet/bin/evaluate.py --save-path ~/results/squares csv test_class_annotation.csv csv/class_mapping_multi.csv snapshots/squares/resnet50_csv_50.h5
